### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mstancamp** [IBM-Bluemix-Docs/openwhisk#102]
There are broken links on the following page:
https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-openwhisk_apigateway#openwhisk_apigateway

Under Modifying the configuration the following three links when clicked result in no page found:
Secure your API
Manage traffic
Socialize and share

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've merged the link fixes. "Secure your API", "Manage traffic", and "Socialize and share" are all done from the API management tab here: https://cloud.ibm.com/openwhisk/apimanagement

**Comment by mstancamp** [comment]
The issue is not fixed. The same problem still occurs when selecting Secure your API from the following links:
https://cloud.ibm.com/apis/managed?env_id=ibm%3Ayp%3Aus-east
https://cloud.ibm.com/openwhisk/apimanagement

I cleared the cache from my browser and the problem still occurs.
